tools:
  # we want to use a pinned version of binny to manage the toolchain (so binny manages itself!)
  - name: binny
    version:
      want: v0.9.0
    method: github-release
    with:
      repo: anchore/binny

  # used for running all local and CI tasks
  - name: task
    version:
      want: v3.41.0
    method: github-release
    with:
      repo: go-task/task

  # used for showing the changelog at release
  - name: glow
    version:
      want: v2.0.0
    method: github-release
    with:
      repo: charmbracelet/glow

  # used at release to generate the changelog
  - name: chronicle
    version:
      want: v0.8.0
    method: github-release
    with:
      repo: anchore/chronicle

  # used at release to generate the changelog
  - name: crane
    version:
      want: v0.20.3
    method: github-release
    with:
      repo: google/go-containerregistry
