"""Release dates for the Go versions the go.dev OSV records name as fixed.

go.dev's records carry no per-fix date, and their `published` field is a
disclosure timestamp rather than a fix-ship date. But for Go the fix *version*
names a published artifact whose release date is knowable, and never changes
once it is known:

- stdlib/toolchain: the committer date of the commit each golang/go release tag
  points at.
- everything else (`golang.org/x/...` and third-party modules): the module
  proxy's `.info` -> `.Time`. For a tagged version that is the commit time of the
  tagged commit, which can predate the tag being pushed -- usually by minutes,
  occasionally by longer. It is still the best per-version date available, so it
  is treated as accurate.

Because the dates are immutable, almost all of them are committed:
`go_release_dates_data` (every golang/go tag) and `go_module_release_dates_data`
(every module fix version in the vulndb), both regenerated by
`task update-go-release-dates`. The committed tables are only as fresh as their
last regeneration, so a run starts with one resolve phase that looks up the
handful of fix versions newer than that, then freezes everything into a
`ReleaseDates` lookup. The per-record loop only ever sees the frozen lookup; it
has no way to reach the network.

The resolve phase is bounded by construction rather than by retry tuning: no
request is ever retried within a run (a miss costs one date until the next run,
which asks again), a host that fails a few times -- or rate-limits us once -- is
not asked again this run, lookups are capped per host, and no request of ours
starts after the phase deadline. So the phase lasts roughly the deadline plus
one request -- "roughly" because a request's timeout bounds each socket read,
not the whole response, so a server dripping bytes can stretch that last
request. And requests go through http_wrapper, whose per-host rate-limit blocks
are process-wide: a block some other caller earned before the resolve phase
started can still delay our first request to that host. Nothing else in vunnel
talks to these hosts today, so the resolver doesn't check for one.

Every failure becomes a missing date and the caller falls back to the advisory's
published date: fix dates are an enrichment, and losing one must not cost the
whole provider run.
"""

from __future__ import annotations

import logging
import re
import time
from datetime import UTC, date, datetime, timedelta
from typing import TYPE_CHECKING, Any
from urllib.parse import urlparse

import orjson
import requests

from vunnel.providers.govulndb.go_module_release_dates_data import GO_MODULE_RELEASE_DATES
from vunnel.providers.govulndb.go_release_dates_data import GO_RELEASE_DATES
from vunnel.tool import fixdate
from vunnel.utils import http_wrapper as http
from vunnel.utils import osv

if TYPE_CHECKING:
    from collections.abc import Callable, Iterable, Mapping

MODULE_PROXY_URL = "https://proxy.golang.org"
GO_GIT_URL = "https://go.googlesource.com/go"

# every upstream the resolve phase may contact, for the provider's `urls`
SOURCE_URLS = (MODULE_PROXY_URL, GO_GIT_URL)

# these map to Go toolchain release tags, not proxy module versions
STDLIB_MODULES = frozenset({"stdlib", "toolchain"})

USER_AGENT = "vunnel/1.0 (govulndb-provider; +https://github.com/anchore/vunnel)"

# single-document metadata reads, not bulk downloads: the provider's download_timeout
# is sized for a multi-megabyte zip. Not shorter, though: the proxy can take ~20s to
# answer a 404 for a version it has never been asked about
DEFAULT_TIMEOUT = 30
# a host that fails this many times is not asked again this run
DEFAULT_MAX_FAILURES_PER_HOST = 3
# lookups allowed per host per run. Normally a run needs a handful; a badly stale
# committed table must not turn into thousands of requests
DEFAULT_MAX_LOOKUPS_PER_HOST = 200
# wall-clock budget for starting requests in the resolve phase
DEFAULT_DEADLINE_SECONDS = 120.0

# Go's first public release. Anything outside [this, tomorrow] is a garbage
# timestamp, not a release date -- and since these are accurate=True and get
# committed, a garbage one would be believed forever.
_EARLIEST_RELEASE = date(2009, 11, 10)

# Module paths and versions come from upstream data and are interpolated into a
# URL, so they are validated against an allowlist rather than escaped: anything
# that could change which URL is being requested -- a scheme, an authority, a
# query, a fragment, a percent-escape, a `..` segment -- is simply not matched.
# The grammar is deliberately narrower than Go's own; a module we cannot express
# safely is one we decline to date. Matched with fullmatch, not match: `$` also
# matches just before a trailing newline, which would let "evil.com/mod\n" through.
_MODULE_PATH_RE = re.compile(r"[a-zA-Z0-9][a-zA-Z0-9._~/-]*")
_MODULE_VERSION_RE = re.compile(r"v?[0-9]+\.[0-9]+(?:\.[0-9]+)?(?:-[0-9a-zA-Z.-]+)?(?:\+[0-9a-zA-Z.-]+)?")
RELEASE_TAG_RE = re.compile(r"go[0-9]+(?:\.[0-9]+){0,2}(?:(?:rc|beta)[0-9]+)?")

# go only ever tags rc and beta prereleases
_PRERELEASE_RE = re.compile(r"(?:rc|beta)[0-9]+")

_MAX_MODULE_PATH_LENGTH = 512
_MAX_MODULE_VERSION_LENGTH = 128


def module_key(module: str, version: str) -> str:
    """How a module fix version is keyed in `go_module_release_dates_data`."""
    return f"{module}@{version}"


def fixed_versions(records: Iterable[Any]) -> set[tuple[str, str]]:
    """Every `(module, fixed version)` pair the given vulndb records name.

    Total over JSON shapes: anything malformed is skipped, never raised on. This runs
    outside the parser's release-date fallback, and a record the rest of the provider
    tolerates must not fail the run here.
    """
    pairs: set[tuple[str, str]] = set()
    for record in records:
        if not isinstance(record, dict):
            continue
        for affected in _dicts(record.get("affected")):
            package = affected.get("package")
            module = package.get("name") if isinstance(package, dict) else None
            if not isinstance(module, str) or not module:
                continue
            for r in _dicts(affected.get("ranges")):
                for event in _dicts(r.get("events")):
                    fixed = event.get("fixed")
                    if isinstance(fixed, str) and fixed:
                        pairs.add((module, fixed))
    return pairs


def _dicts(value: Any) -> list[dict[str, Any]]:
    """The dict elements of `value` if it is a list, else nothing."""
    return [v for v in value if isinstance(v, dict)] if isinstance(value, list) else []


class ReleaseDates:
    """A frozen `(module, version) -> release date` lookup. Never touches the network."""

    def __init__(self, stdlib: Mapping[str, date], modules: Mapping[str, date]):
        self._stdlib = dict(stdlib)
        self._modules = dict(modules)

    def lookup(self, module: object, version: object) -> date | None:
        # the record loop passes raw OSV values straight from the advisory, outside any
        # fallback, so anything that isn't a non-empty string is a miss, not a crash
        if not isinstance(module, str) or not isinstance(version, str) or not module or not version:
            return None
        if module in STDLIB_MODULES:
            tag = stdlib_version_to_tag(version)
            return self._stdlib.get(tag) if tag else None
        return self._modules.get(module_key(module, version))


class _HostBudget:
    """Per-host failure accounting and lookup caps, plus a phase deadline."""

    def __init__(
        self,
        logger: logging.Logger,
        max_failures: int,
        max_lookups: int,
        deadline_seconds: float | None,
        clock: Callable[[], float],
    ):
        self.logger = logger
        self.max_failures = max_failures
        self.max_lookups = max_lookups
        self.clock = clock
        self.deadline = clock() + deadline_seconds if deadline_seconds is not None else None
        self.failures: dict[str, int] = {}
        self.lookups: dict[str, int] = {}
        self.down: set[str] = set()
        self._warned_deadline = False
        self._warned_cap: set[str] = set()

    def allow(self, host: str) -> bool:
        if host in self.down:
            return False
        if self.deadline is not None and self.clock() >= self.deadline:
            if not self._warned_deadline:
                self._warned_deadline = True
                self.logger.warning("go release-date resolve deadline reached; remaining fix versions keep their fallback date this run")
            return False
        if self.lookups.get(host, 0) >= self.max_lookups:
            if host not in self._warned_cap:
                self._warned_cap.add(host)
                self.logger.warning(
                    f"reached the {self.max_lookups}-lookup cap for {host}; the committed go release-date table is "
                    "likely stale (run `task update-go-release-dates`)",
                )
            return False
        self.lookups[host] = self.lookups.get(host, 0) + 1
        return True

    def fail(self, host: str, reason: str, fatal: bool = False) -> None:
        self.failures[host] = self.failures.get(host, 0) + 1
        if fatal or self.failures[host] >= self.max_failures:
            self.down.add(host)
            self.logger.warning(f"not contacting {host} again this run: {reason}")
        else:
            self.logger.debug(f"go release-date request to {host} failed: {reason}")


class ReleaseDateResolver:
    """Resolve release dates for a set of fix versions, outside the per-record loop.

    `resolve()` subtracts what the committed tables already know, asks the upstreams
    about the rest one at a time, and returns a frozen `ReleaseDates`. With
    `offline=True` (the provider's `skip_download`) nothing is fetched.

    Requests go through `http_wrapper`, so they share its per-host rate-limit state
    with the rest of vunnel. The wrapper serializes requests per host, which is fine
    here: past a fresh regeneration there are only a handful to make.
    """

    def __init__(  # noqa: PLR0913
        self,
        logger: logging.Logger | None = None,
        offline: bool = False,
        timeout: int = DEFAULT_TIMEOUT,
        max_failures_per_host: int = DEFAULT_MAX_FAILURES_PER_HOST,
        max_lookups_per_host: int = DEFAULT_MAX_LOOKUPS_PER_HOST,
        deadline_seconds: float | None = DEFAULT_DEADLINE_SECONDS,
        stdlib_table: Mapping[str, str] | None = None,
        module_table: Mapping[str, str | None] | None = None,
        clock: Callable[[], float] = time.monotonic,
    ):
        self.logger = logger if logger is not None else logging.getLogger(self.__class__.__name__)
        # http_wrapper logs a WARNING and an ERROR for every failed attempt; here a failed
        # lookup is an expected, already-handled miss that the budget reports on its own
        self._http_logger = self.logger.getChild("http")
        self._http_logger.setLevel(logging.CRITICAL)
        self.offline = offline
        self.timeout = timeout
        self.max_failures_per_host = max_failures_per_host
        self.max_lookups_per_host = max_lookups_per_host
        self.deadline_seconds = deadline_seconds
        self.stdlib_table = GO_RELEASE_DATES if stdlib_table is None else stdlib_table
        self.module_table = GO_MODULE_RELEASE_DATES if module_table is None else module_table
        self.clock = clock

    def committed(self) -> ReleaseDates:
        """What the committed tables alone know. Never touches the network."""
        return ReleaseDates(_parse_table(self.stdlib_table, self.logger), _parse_table(self.module_table, self.logger))

    def resolve(self, pairs: Iterable[tuple[str, str]]) -> ReleaseDates:
        stdlib = _parse_table(self.stdlib_table, self.logger)
        modules = _parse_table(self.module_table, self.logger)

        missing_tags, missing_modules = self._missing(pairs)
        if not missing_tags and not missing_modules:
            return ReleaseDates(stdlib, modules)

        if self.offline:
            self.logger.info(
                f"skip_download is set: {len(missing_tags) + len(missing_modules)} go fix versions are newer than the "
                "committed release-date tables and keep their fallback date",
            )
            return ReleaseDates(stdlib, modules)

        self.logger.info(
            f"resolving release dates for {len(missing_tags)} go releases and {len(missing_modules)} module versions not in the committed tables",
        )
        budget = self._budget()

        for tag in sorted(missing_tags):
            if d := self._resolve_tag(budget, tag):
                stdlib[tag] = d
        for module, version in sorted(missing_modules):
            if d := self._resolve_module(budget, module, version):
                modules[module_key(module, version)] = d

        return ReleaseDates(stdlib, modules)

    def _missing(self, pairs: Iterable[tuple[str, str]]) -> tuple[set[str], set[tuple[str, str]]]:
        """The release tags and module versions the committed tables don't cover."""
        missing_tags: set[str] = set()
        missing_modules: set[tuple[str, str]] = set()
        for module, version in pairs:
            if module in STDLIB_MODULES:
                tag = stdlib_version_to_tag(version)
                if tag and tag not in self.stdlib_table:
                    missing_tags.add(tag)
            # a committed None is a version the proxy doesn't know; don't ask again every run
            elif module_key(module, version) not in self.module_table:
                missing_modules.add((module, version))
        return missing_tags, missing_modules

    def _resolve_tag(self, budget: _HostBudget, tag: str) -> date | None:
        url = _stdlib_tag_url(tag)
        if url is None:
            return None
        body = self._fetch(budget, url)
        return _stdlib_release_date(_decode_json(_strip_xss_guard(body), url, self.logger)) if body else None

    def _resolve_module(self, budget: _HostBudget, module: str, version: str) -> date | None:
        url = module_info_url(module, version)
        if url is None:
            self.logger.debug(f"cannot build a safe proxy URL for {module!r}@{version!r}; no date for it")
            return None
        body = self._fetch(budget, url)
        return parse_module_info(body, url, self.logger) if body else None

    def _fetch(self, budget: _HostBudget, url: str) -> bytes | None:
        """One attempt, never retried. The body of a 200, or None for anything else."""
        host = urlparse(url).netloc
        if not budget.allow(host):
            return None
        # network errors are misses that count against the host; anything else is a bug and
        # propagates to the parser's fallback, which logs the traceback
        try:
            resp = http.get(
                url,
                self._http_logger,
                retries=0,
                timeout=self.timeout,
                status_handler=_answered_or_raise,
                user_agent=USER_AGENT,
                # Neither upstream redirects these reads (every committed module version and
                # every sampled tag answers in place, vanity paths included: the proxy resolves
                # those itself). A redirect means something unexpected, and following it would
                # skip the URL allowlist and the per-host budget, so it's a failed lookup.
                allow_redirects=False,
            )
        except requests.HTTPError as e:
            status = e.response.status_code if e.response is not None else None
            # A rate limit means stop, not wait: every date here has a fallback. It must be
            # http_wrapper's own definition (429, or 503 with Retry-After): the wrapper has
            # just marked the host blocked, and would sleep out the block inside our next
            # request to it, where the deadline can't reach.
            rate_limited = e.response is not None and http._is_rate_limited(e.response)  # noqa: SLF001
            budget.fail(host, f"HTTP {status} from {url}", fatal=rate_limited)
            return None
        except requests.RequestException as e:
            budget.fail(host, f"{type(e).__name__}: {e}")
            return None

        if resp.status_code != 200:
            self.logger.debug(f"no release-date record at {url} (HTTP {resp.status_code})")
            return None
        return resp.content

    def _budget(self) -> _HostBudget:
        return _HostBudget(
            logger=self.logger,
            max_failures=self.max_failures_per_host,
            max_lookups=self.max_lookups_per_host,
            deadline_seconds=self.deadline_seconds,
            clock=self.clock,
        )


def _answered_or_raise(response: requests.Response) -> None:
    """http_wrapper status handler: 200 is an answer and 404/410 mean "unknown version" --
    also an answer, not a failure. Everything else, a 3xx included (raise_for_status lets
    those through), is a failure that counts against the host."""
    if response.status_code not in (200, 404, 410):
        raise requests.HTTPError(f"HTTP {response.status_code} for url: {getattr(response, 'url', '')}", response=response)


def go_extra_candidates(dates: ReleaseDates) -> osv.ExtraCandidatesCallable:
    """Build the extra-candidates callable for osv.patch_fix_date.

    accurate=True ranks the release date ahead of the advisory's low-confidence
    published date and any inaccurate first-observed date. An accurate first-observed
    date still caps it: Finder.best returns the first-observed date instead when the
    release date is later.
    """

    def candidates(vuln_id: str, package_name: str, fix_version: str, ecosystem: str | None) -> list[fixdate.Result]:
        d = dates.lookup(package_name, fix_version)
        if d is None:
            return []
        return [fixdate.Result(date=d, kind="release", accurate=True)]

    return candidates


def stdlib_version_to_tag(version: str) -> str | None:
    """Map a go vuln db stdlib version to its golang/go release tag, or None.

    Prereleases use the toolchain's compact form (`1.27.0-rc.3` -> `go1.27rc3`);
    the go vuln db lists them because an upcoming minor's RC is often the first
    artifact carrying a fix. Releases drop the `.0` only below 1.21 -- Go tagged
    the 1.20 series `go1.20`, `go1.20.1`, ... and only started tagging `goX.Y.0`
    at `go1.21.0`.

    Returns None for a version that names no released artifact. Go only tags
    `rc` and `beta` prereleases, so govulndb's semver floor `1.21.0-0` -- which
    means "every 1.21 prerelease and later", used to say the `toolchain` module
    did not exist before 1.21 -- has no tag.
    """
    v = version.removeprefix("go")
    if "-" in v:
        base, _, pre = v.partition("-")
        pre = pre.replace(".", "")
        if not _PRERELEASE_RE.fullmatch(pre):
            return None
        tag = f"go{base.removesuffix('.0')}{pre}"
    else:
        tag = f"go{_release_tag_body(v)}"
    return tag if RELEASE_TAG_RE.fullmatch(tag) else None


def _release_tag_body(version: str) -> str:
    """`1.20.0` -> `1.20`, but leave `1.21.0` and later alone (see stdlib_version_to_tag)."""
    base = version.removesuffix(".0")
    if base == version:
        return version
    try:
        major, minor = (int(part) for part in base.split(".", 1))
    except ValueError:
        return version
    return base if (major, minor) < (1, 21) else version


def module_info_url(module: str, version: str) -> str | None:
    """The proxy `.info` URL for a module version, or None if it cannot be built safely."""
    if not _valid_module_path(module) or len(version) > _MAX_MODULE_VERSION_LENGTH or not _MODULE_VERSION_RE.fullmatch(version):
        return None
    v = version if version.startswith("v") else f"v{version}"
    return f"{MODULE_PROXY_URL}/{_escape_module_path(module)}/@v/{_escape_module_path(v)}.info"


def parse_module_info(body: bytes, url: str, logger: logging.Logger) -> date | None:
    """The release date in a proxy `.info` body, or None."""
    payload = _decode_json(body, url, logger)
    if not payload:
        return None
    return _parse_iso_date(payload.get("Time"))


def _valid_module_path(module: str) -> bool:
    if len(module) > _MAX_MODULE_PATH_LENGTH or not _MODULE_PATH_RE.fullmatch(module):
        return False
    # `.` and `-` are legal in a path element but `.`/`..` elements are not, and
    # neither are empty ones: both would re-point the URL somewhere else
    return all(segment not in ("", ".", "..") for segment in module.split("/"))


def _stdlib_tag_url(tag: str) -> str | None:
    if not RELEASE_TAG_RE.fullmatch(tag):
        return None
    return f"{GO_GIT_URL}/+/refs/tags/{tag}?format=JSON"


def _escape_module_path(module: str) -> str:
    """Module proxy path escaping: uppercase becomes `!` + lowercase.

    Applies to the version as well as the module path -- the proxy's case-encoding
    rule covers every path element it serves.
    """
    return "".join(f"!{c.lower()}" if c.isupper() else c for c in module)


def _strip_xss_guard(body: bytes) -> bytes:
    # gitiles prefixes JSON with a `)]}'` XSS-guard line that must be stripped
    return body.split(b"\n", 1)[1] if body.startswith(b")]}'") and b"\n" in body else body


def _decode_json(body: bytes, url: str, logger: logging.Logger) -> dict[str, Any] | None:
    try:
        payload = orjson.loads(body)
    except orjson.JSONDecodeError as e:
        logger.warning(f"ignoring unparseable release-date response from {url}: {e}")
        return None
    if not isinstance(payload, dict):
        logger.warning(f"ignoring unexpected release-date response from {url}: not a JSON object")
        return None
    return payload


def _stdlib_release_date(payload: dict[str, Any] | None) -> date | None:
    if not payload:
        return None
    # committer time is the release commit on the release branch
    committer = payload.get("committer") or payload.get("author") or {}
    if not isinstance(committer, dict):
        return None
    return _parse_gitiles_time(committer.get("time"))


def _parse_table(table: Mapping[str, str | None], logger: logging.Logger) -> dict[str, date]:
    out: dict[str, date] = {}
    for key, released in table.items():
        if released is None:
            continue
        try:
            out[key] = date.fromisoformat(released)
        except (ValueError, TypeError):
            # the tables are generated, so this means one was hand-edited into something invalid
            logger.warning(f"committed go release-date table has an invalid date for {key}: {released!r}")
    return out


def _parse_iso_date(s: str | None) -> date | None:
    """Parse an ISO-8601 timestamp (e.g. `2023-08-01T17:46:51Z`) as a UTC date."""
    if not isinstance(s, str) or not s:
        return None
    try:
        parsed = datetime.fromisoformat(s)
    except ValueError:
        return None
    return _as_utc_date(parsed)


def _parse_gitiles_time(s: str | None) -> date | None:
    """Parse a gitiles git-time string, e.g. `Tue Dec 05 18:12:56 2023 +0000`, as a UTC date."""
    if not isinstance(s, str) or not s:
        return None
    try:
        parsed = datetime.strptime(s, "%a %b %d %H:%M:%S %Y %z")
    except ValueError:
        return None
    return _as_utc_date(parsed)


def _as_utc_date(value: datetime) -> date | None:
    """The UTC calendar date of a timestamp, or None if it can't be a Go release.

    Release commits are tagged from whatever timezone the release runner sits in
    (`-0800` for most go releases), so the local date and the UTC date disagree
    for late-in-the-day releases. Normalizing means one release has one date
    whichever source answered, and matches how every other date in vunnel reads.
    """
    try:
        d = value.date() if value.tzinfo is None else value.astimezone(UTC).date()
    except OverflowError:
        # e.g. year 1 with a positive offset: there is no UTC date to convert to
        return None
    return d if is_plausible_release_date(d) else None


def is_plausible_release_date(d: date) -> bool:
    """Whether `d` could be a Go release: no earlier than Go's first, no later than tomorrow.

    Shared by every path that produces a date -- runtime lookups and both halves of the
    generator -- because a date outside this window is garbage that, being accurate=True,
    would otherwise be believed (and committed) forever.
    """
    return _EARLIEST_RELEASE <= d <= datetime.now(UTC).date() + timedelta(days=1)
